employee_policy_task:
  description: >
    Retrieve and summarize the requested HR policy from the official HR policy
    documents using the RAGPolicyTool. Ensure the explanation is accurate,
    compliant, and easy for non-HR staff to understand. If the employee asks
    about a specific clause, provide the exact section and context.

    The specific employee question is: {query}
  expected_output: >
    A concise, plain-language summary of the requested HR policy with clear
    references to the source document and clause numbers where applicable.
  agent: policy_retriever

leave_task:
  description: >
    Answer employee questions about leave policies, including sick leave,
    vacation leave, and emergency leave. Ensure all responses strictly follow
    the company’s official HR policy. Use empathetic tone and clarify any
    approval procedures.

    The specific employee question is: {query}
  expected_output: >
    A complete explanation of leave entitlements, conditions, and procedures,
    formatted as a short employee-facing note.
  agent: hr_expert

benefits_task:
  description: >
    Explain employee benefits such as healthcare, retirement plans,
    allowances, and bonuses. Ensure details match official HR policy documents
    and current company offerings.

    The specific employee question is: {query}
  expected_output: >
    A well-structured summary or list of relevant benefits, including
    eligibility rules and any limitations.
  agent: hr_expert

compliance_task:
  description: >
    Handle compliance-related employee queries, referencing both internal
    HR policies and applicable labor regulations. Ensure answers are legally
    accurate and clearly connected to the company’s compliance framework.

    The specific employee question is: {query}
  expected_output: >
    A policy-compliant answer referencing the correct company regulation or
    legal clause in plain language.
  agent: hr_expert

onboarding_task:
  description: >
    Support new employees during onboarding by explaining the steps, required
    documents, internal systems, and key contacts. Personalize guidance based
    on the employee’s role or department.

    The specific employee question is: {query}
  expected_output: >
    A clear, actionable onboarding checklist or step-by-step guide for
    the new hire’s first week.
  agent: hr_expert

performance_task:
  description: >
    Provide detailed information about performance evaluations, review
    schedules, rating criteria, and career development opportunities. Emphasize
    fairness, transparency, and growth.

    The specific employee question is: {query}
  expected_output: >
    A structured explanation of the performance review process, timeline,
    and evaluation criteria presented in an easy-to-follow format.
  agent: hr_expert
